import { Certificate } from "../achievements.types";

export const certificates: Certificate[] = [
	{
		slug: "meta-frontend-developer",
		title: "Meta Front-End Developer",
		issuer: "Meta / Coursera",
		date: "2024",
		image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80&auto=format&fit=crop",
		description: "Professional certificate covering React, JavaScript, HTML/CSS, and UX design principles.",
		story: `I started this certificate when I realised my self-taught React knowledge had gaps — I knew how to build things but not always why. The Meta program forced me to go back to fundamentals: semantic HTML, CSS specificity, and JavaScript under the hood before touching React at all.\n\nThe hardest part was the capstone project, where I had to build a fully functioning restaurant booking app from scratch with no hints. It pushed me to read documentation properly instead of copying Stack Overflow answers.\n\nAfter finishing, my debugging speed noticeably improved because I finally understood the render cycle properly.`,
		skills: ["React", "JavaScript", "HTML", "CSS", "UX Design", "Version Control"],
		resources: [
			{ title: "Meta Front-End Developer on Coursera", url: "https://coursera.org" },
			{ title: "React Documentation", url: "https://react.dev" },
		],
		credentialUrl: "",
	},
	{
		slug: "responsive-web-design",
		title: "Responsive Web Design",
		issuer: "freeCodeCamp",
		date: "2023",
		image: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&q=80&auto=format&fit=crop",
		description: "300-hour certification covering HTML5, CSS3, Flexbox, CSS Grid, and responsive design patterns.",
		story: `This was my very first certificate — I earned it during my second year at MIIT when I was still figuring out if web development was something I genuinely wanted to pursue.\n\nFreeCodeCamp's project-based approach was eye-opening. Building a tribute page and a product landing page from scratch with no starter code taught me how to think structurally about layouts before touching any CSS.\n\nThe responsive design modules changed how I think about screens. I stopped thinking "make it work on desktop" and started thinking "design for the smallest screen first." That shift still influences how I write CSS today.`,
		skills: ["HTML5", "CSS3", "Flexbox", "CSS Grid", "Responsive Design"],
		resources: [
			{ title: "freeCodeCamp Responsive Web Design", url: "https://freecodecamp.org" },
			{ title: "CSS Tricks - A Complete Guide to Flexbox", url: "https://css-tricks.com/snippets/css/a-guide-to-flexbox" },
		],
		credentialUrl: "",
	},
	{
		slug: "javascript-algorithms",
		title: "JavaScript Algorithms & Data Structures",
		issuer: "freeCodeCamp",
		date: "2023",
		image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&q=80&auto=format&fit=crop",
		description: "300-hour certification covering ES6+, regular expressions, debugging, OOP, and functional programming.",
		story: `After the responsive design cert I wanted to stop avoiding JavaScript properly. I had been writing jQuery snippets without understanding closures, prototypes, or what 'this' actually meant.\n\nThe algorithms section broke me — in a good way. Solving the Caesar Cipher and palindrome checker with no hints took me hours each. I started keeping a notebook of patterns I discovered, which became a habit I still have.\n\nThis certificate is the reason I could confidently call myself a JavaScript developer rather than someone who copies code. Understanding scope and closures unlocked React for me shortly after.`,
		skills: ["JavaScript", "ES6+", "Algorithms", "Data Structures", "OOP", "Functional Programming"],
		resources: [
			{ title: "freeCodeCamp JS Algorithms", url: "https://freecodecamp.org" },
			{ title: "You Don't Know JS (Book Series)", url: "https://github.com/getify/You-Dont-Know-JS" },
		],
		credentialUrl: "",
	},
	{
		slug: "react-basics",
		title: "React Basics",
		issuer: "Meta / Coursera",
		date: "2023",
		image: "https://images.unsplash.com/photo-1581276879432-15e50529f34b?w=800&q=80&auto=format&fit=crop",
		description: "Foundation certificate covering React components, state, props, hooks, and the virtual DOM.",
		story: `I took this after completing the JavaScript cert. React felt intimidating — JSX looked wrong and the component model was confusing coming from plain HTML/JS.\n\nWhat clicked for me was thinking of components like LEGO blocks. Once I stopped thinking in pages and started thinking in reusable pieces, the mental model snapped into place.\n\nThe hooks section (useState, useEffect) took the most effort. I broke countless toy apps trying to understand when effects run and why they sometimes cause infinite loops. Each bug I fixed taught me more than the course videos did.`,
		skills: ["React", "JSX", "Hooks", "Components", "State Management", "Props"],
		resources: [
			{ title: "React Basics on Coursera", url: "https://coursera.org" },
			{ title: "React Official Docs", url: "https://react.dev" },
		],
		credentialUrl: "",
	},
	{
		slug: "version-control",
		title: "Version Control",
		issuer: "Meta / Coursera",
		date: "2023",
		image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80&auto=format&fit=crop",
		description: "Certificate covering Git fundamentals, branching strategies, GitHub workflows, and collaborative development.",
		story: `Before this I was using Git as a backup tool — just committing everything to main with messages like "fix" or "update". I knew it was wrong but didn't know what right looked like.\n\nLearning branching strategy (feature branches, PR reviews, merge vs rebase) transformed how I work. I started treating every personal project as if a team might read my commits, which made me write better commit messages.\n\nGitHub Actions was the bonus revelation. Seeing CI run automatically on a push made the DevOps world feel suddenly accessible rather than mysterious.`,
		skills: ["Git", "GitHub", "Branching", "Pull Requests", "CI/CD Basics", "Collaborative Workflow"],
		resources: [
			{ title: "Version Control on Coursera", url: "https://coursera.org" },
			{ title: "Git Documentation", url: "https://git-scm.com/doc" },
		],
		credentialUrl: "",
	},
];
